(function () {
    'use strict';
    const state = { data: null, initialized: false };
    const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
    const apiBase = () => window.backendUrl || window.getBackendUrl?.() || window.location.origin;
    const headers = () => typeof window.authHeaders === 'function' ? window.authHeaders() : {};
    async function request(path) { const response = await fetch(`${apiBase()}/api/asistente-capacitacion${path}`, {headers: headers()}); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'No se pudo consultar el Manual Maestro.'); return data; }
    function render(data, query = '') {
        const target = document.getElementById('liam-manual-content'); if (!target) return;
        const needle = query.trim().toLocaleLowerCase('es'); const matches = item => !needle || JSON.stringify(item).toLocaleLowerCase('es').includes(needle);
        const modules = (data.modules || []).filter(matches), workflows = (data.workflows || []).filter(matches), errors = (data.errors || []).filter(matches);
        target.innerHTML = `<div class="flex flex-wrap gap-2 text-xs text-slate-400 mb-4"><span class="rounded-full border border-cyan-500/30 px-3 py-1">Rol: ${escapeHtml(data.role_guide?.title || data.role)}</span><span class="rounded-full border border-slate-700 px-3 py-1">Guía: ${escapeHtml(data.metadata?.guide_version)}</span><span class="rounded-full border border-slate-700 px-3 py-1">Verificado: ${escapeHtml(data.metadata?.last_verified_at)}</span></div>
        ${modules.map(module => `<article class="rounded-xl border border-slate-800 bg-slate-950/50 p-4 mb-3"><h4 class="font-semibold text-cyan-100">${escapeHtml(module.title)}</h4><p class="mt-1 text-sm text-slate-300">${escapeHtml(module.objective)}</p><p class="mt-2 text-xs text-slate-400"><strong>Ubicación:</strong> ${escapeHtml(module.location)}</p><p class="mt-1 text-xs text-slate-400"><strong>Requisitos:</strong> ${escapeHtml((module.prerequisites || []).join(' · '))}</p><ol class="mt-2 list-decimal pl-5 text-sm text-slate-300">${(module.process || []).map(step => `<li>${escapeHtml(step)}</li>`).join('')}</ol>${(module.controls || []).map(control => `<div class="mt-3 rounded-lg border border-indigo-500/25 bg-indigo-500/5 p-3"><p class="text-sm font-medium text-indigo-200">${escapeHtml(control.title)}</p><code class="text-xs text-slate-500">${escapeHtml(control.help_id)}</code><p class="mt-1 text-xs text-slate-300">${escapeHtml(control.purpose)}</p><p class="mt-1 text-xs text-emerald-300">Siguiente: ${escapeHtml(control.next_step)}</p></div>`).join('')}</article>`).join('')}
        ${workflows.length ? `<h4 class="mt-6 mb-3 font-semibold text-white">Guías rápidas</h4>${workflows.map(flow => `<article class="rounded-xl border border-slate-800 p-4 mb-3"><h5 class="text-amber-200">${escapeHtml(flow.title)}</h5><ol class="mt-2 list-decimal pl-5 text-sm text-slate-300">${flow.steps.map(step => `<li>${escapeHtml(step)}</li>`).join('')}</ol>${flow.important ? `<p class="mt-2 text-xs text-amber-300">${escapeHtml(flow.important)}</p>` : ''}</article>`).join('')}` : ''}
        ${errors.length ? `<h4 class="mt-6 mb-3 font-semibold text-white">Errores y soluciones</h4>${errors.map(error => `<details class="rounded-xl border border-rose-500/20 p-3 mb-2"><summary class="cursor-pointer text-sm text-rose-200">${escapeHtml(error.code)} — ${escapeHtml(error.title)}</summary><p class="mt-2 text-xs text-slate-300">${escapeHtml(error.explanation)}</p><p class="mt-1 text-xs text-emerald-300">${escapeHtml(error.action)}</p></details>`).join('')}` : ''}${!modules.length && !workflows.length && !errors.length ? '<p class="text-sm text-slate-400">No hay resultados dentro de las guías autorizadas para tu rol.</p>' : ''}`;
    }
    async function load() { const target = document.getElementById('liam-manual-content'); if (!target) return; target.innerHTML = '<p class="text-sm text-slate-400">Consultando las guías autorizadas para tu rol…</p>'; try { state.data = await request('/manual'); render(state.data, document.getElementById('liam-manual-search')?.value || ''); } catch (error) { target.innerHTML = `<p class="text-sm text-rose-300">${escapeHtml(error.message)}</p>`; } }
    async function downloadPdf() { const response = await fetch(`${apiBase()}/api/asistente-capacitacion/manual.pdf`, {headers: headers()}); if (!response.ok) throw new Error('No se pudo descargar el manual PDF.'); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = 'Manual_Maestro_Primera_Infancia.pdf'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); }
    function registerContext(event) { const control = event.target.closest?.('[data-help-id]'); if (!control) return; window.LIAM_CURRENT_CONTEXT = {module_id: control.dataset.helpModule || location.hash.slice(1) || 'dashboard', screen_id: control.dataset.helpScreen || '', active_help_id: control.dataset.helpId || ''}; document.dispatchEvent(new CustomEvent('liam:context-changed', {detail: window.LIAM_CURRENT_CONTEXT})); }
    function init() { if (state.initialized) return; state.initialized = true; document.addEventListener('click', registerContext, true); document.addEventListener('focusin', registerContext, true); document.getElementById('liam-manual-search')?.addEventListener('input', event => state.data && render(state.data, event.target.value)); document.getElementById('liam-manual-refresh')?.addEventListener('click', load); document.getElementById('liam-manual-pdf')?.addEventListener('click', () => downloadPdf().catch(error => alert(error.message))); document.getElementById('nav-manual-operativo')?.addEventListener('click', load); }
    document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', init) : init();
    window.LIAM_MANUAL = {load, getContext: () => ({...window.LIAM_CURRENT_CONTEXT})};
})();
