from __future__ import annotations

CATALOG_VERSION = "2026.08.2"

CANONICAL_FIELDS = {
    "tenant.id": {"aliases": ["tenant id", "fundacion id", "corporacion id"]},
    "institucion.nombre": {"aliases": ["nombre institucion", "institucion", "entidad"]},
    "institucion.nit": {"aliases": ["nit institucion", "nit entidad"]},
    "entidad_contratista.nombre": {"aliases": ["nombre entidad contratista", "contratista", "operador"]},
    "entidad_contratista.nit": {"aliases": ["nit entidad contratista", "nit contratista", "nit operador"]},
    "contrato.numero": {"aliases": ["numero contrato", "contrato numero", "contrato"]},
    "contrato.regional": {"aliases": ["regional contrato", "contrato regional"]},
    "contrato.modalidad": {"aliases": ["modalidad contrato", "modalidad del contrato"]},
    "programa.modalidad": {"aliases": ["modalidad programa", "modalidad del programa", "modalidad del servicio"]},
    "programa.comunidad": {"aliases": ["comunidad del programa", "comunidad asignada", "comunidad"]},
    "regional.nombre": {"aliases": ["nombre regional", "regional", "nombre de la regional de la unidad de servicio"]},
    "departamento.codigo": {"aliases": ["codigo departamento", "codigo dane departamento"]},
    "departamento.nombre": {"aliases": ["nombre departamento", "departamento"]},
    "municipio.codigo": {"aliases": ["codigo municipio", "codigo del municipio de la unidad de servicio"]},
    "municipio.nombre": {"aliases": ["nombre municipio", "nombre municipio de la unidad de servicio"]},
    "centro_zonal.nombre": {"aliases": ["nombre centro zonal", "nombre del centro zonal", "centro zonal"]},
    "centro_zonal.codigo": {"aliases": ["codigo centro zonal", "id centro zonal"]},
    "unidad.codigo": {"aliases": ["codigo de la unidad de servicio", "codigo unidad de servicio", "codigo unidad servicio", "codigo uds", "id unidad de servicio", "id uds", "identificador de unidad"]},
    "unidad.nombre": {"aliases": ["nombre de la unidad de servicio", "nombre unidad de servicio", "nombre unidad servicio", "nombre de la uds", "nombre uds", "unidad de servicio", "unidad servicio", "uds", "nombre sede", "nombre centro de atencion", "punto de atencion"]},
    "unidad.tipo": {"aliases": ["tipo unidad", "tipo de unidad", "clase unidad"]},
    "unidad.modalidad": {"aliases": ["modalidad unidad", "modalidad del servicio", "modalidad"]},
    "unidad.direccion": {"aliases": ["direccion unidad", "direccion uds", "direccion sede"]},
    "unidad.estado": {"aliases": ["estado unidad", "estado uds"]},
    "unidad.cupo": {"aliases": ["cupo unidad", "cobertura unidad", "capacidad uds"]},
    "participante.tipo_documento": {"aliases": ["tipo documento beneficiario", "tipo de documento del beneficiario", "tipo documento"]},
    "participante.numero_documento": {"aliases": ["documento del beneficiario", "numero documento beneficiario", "numero de documento", "documento"]},
    "participante.nui": {"aliases": ["nui", "numero unico identificacion"]},
    "participante.nombre_completo": {"aliases": ["nombre completo beneficiario", "nombres y apellidos", "beneficiario"]},
    "participante.primer_nombre": {"aliases": ["primer nombre del beneficiario", "primer nombre"]},
    "participante.segundo_nombre": {"aliases": ["segundo nombre del beneficiario", "segundo nombre"]},
    "participante.primer_apellido": {"aliases": ["primer apellido del beneficiario", "primer apellido"]},
    "participante.segundo_apellido": {"aliases": ["segundo apellido del beneficiario", "segundo apellido"]},
    "participante.fecha_nacimiento": {"aliases": ["fecha de nacimiento del beneficiario", "fecha nacimiento"]},
    "participante.sexo": {"aliases": ["sexo del beneficiario", "sexo", "genero"]},
    "participante.estado": {"aliases": ["estado del beneficiario", "estado beneficiario"]},
    "participante.grupo_etario": {"aliases": ["grupo etario", "grupo de edad", "tipo de beneficiario"]},
    "participante.edad": {"aliases": ["edad beneficiario", "edad", "edad anos"]},
    "participante.fecha_ingreso": {"aliases": ["fecha ingreso", "fecha atencion beneficiario uds", "fecha de atencion del beneficiario a la uds"]},
    "participante.fecha_retiro": {"aliases": ["fecha retiro", "fecha de retiro"]},
    "acudiente.tipo_documento": {"aliases": ["tipo documento acudiente", "tipo identificacion acudiente"]},
    "acudiente.numero_documento": {"aliases": ["documento acudiente", "numero documento acudiente"]},
    "acudiente.nombre_completo": {"aliases": ["nombre acudiente", "nombre completo acudiente", "responsable familiar"]},
    "acudiente.telefono": {"aliases": ["telefono acudiente", "celular acudiente", "contacto acudiente"]},
    "acudiente.direccion": {"aliases": ["direccion acudiente", "direccion familia"]},
    "acudiente.parentesco": {"aliases": ["parentesco acudiente", "parentesco"]},
    "acudiente.tipo_responsable": {"aliases": ["tipo de responsable", "tipo responsable", "clase de responsable"]},
    "nutricion.fecha_medicion": {"aliases": ["fecha medicion", "fecha toma", "fecha valoracion"]},
    "nutricion.peso_kg": {"aliases": ["peso kg", "peso"]},
    "nutricion.talla_cm": {"aliases": ["talla cm", "talla", "estatura"]},
    "nutricion.perimetro_braquial_cm": {"aliases": ["perimetro braquial cm", "perimetro braquial", "pb"]},
    "nutricion.diagnostico": {"aliases": ["diagnostico nutricional", "estado nutricional", "diagnostico"]},
    "nutricion.vacunacion": {"aliases": ["esquema vacunacion", "vacunacion", "vacunas"]},
    "talento_humano.tipo_documento": {"aliases": ["tipo documento talento humano", "tipo documento empleado"]},
    "talento_humano.numero_documento": {"aliases": ["documento talento humano", "documento empleado"]},
    "talento_humano.nombre_completo": {"aliases": ["nombre talento humano", "nombre empleado", "nombre colaborador"]},
    "talento_humano.cargo": {"aliases": ["cargo talento humano", "cargo", "rol empleado"]},
    "talento_humano.unidad_codigo": {"aliases": ["codigo unidad talento humano", "codigo uds empleado"]},
    "talento_humano.unidad_nombre": {"aliases": ["unidad talento humano", "uds empleado", "unidad empleado"]},
}

NEGATIVE_TERMS = {
    "unidad.nombre": {"regional": -120, "municipio": -120, "departamento": -120, "centro zonal": -110, "distrito": -110, "contrato": -100, "entidad": -100, "operador": -100, "codigo": -80, "documento": -100},
    "unidad.codigo": {"regional": -120, "departamento": -120, "municipio": -120, "centro zonal": -120, "contrato": -100, "operador": -100, "beneficiario": -120, "documento": -120, "nui": -120},
}

FORMAT_REQUIREMENTS = {
    "RAM": {"required": ["unidad.codigo", "unidad.nombre", "participante.numero_documento", "participante.nombre_completo"], "optional": ["participante.nui", "participante.fecha_nacimiento"]},
    "RPP": {"required": ["unidad.codigo", "unidad.nombre", "participante.nombre_completo", "participante.fecha_nacimiento", "participante.grupo_etario"]},
    "BIENESTARINA": {"required": ["unidad.codigo", "unidad.nombre", "participante.numero_documento", "participante.nombre_completo"]},
    "LISTADO_ASISTENCIA": {"required": ["unidad.codigo", "unidad.nombre", "participante.numero_documento", "participante.nombre_completo"]},
}
